# Generated by Django 3.2.6 on 2021-08-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=200)),
                ('files', models.FileField(upload_to='jobs/')),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('Java', 'java'), ('Python', 'py')], max_length=50)),
                ('baseFile', models.CharField(max_length=200)),
            ],
        ),
    ]
