# Generated by Django 3.1.2 on 2021-08-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('userEmail', models.EmailField(max_length=200)),
                ('files', models.FileField(upload_to='jobs/')),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
